### ISSUE TITLE
only shows id

### ISSUE THREAD

**Issue by GrizzlyKt** [Pandiora/SteamAccountRoboticAssistant#23]
hello i open the robotic put my details in all i get is my user name and badge no games no cards  -30 csgo cards thank you for any help regards Grizzlykt

**Comment by Pandiora** [comment]
Hello @GrizzlyKt ,

I told you [here](https://github.com/Pandiora/SteamAccountRoboticAssistant/issues/22), that I don't want to invest further development and time into the "old" overview and just fixed the loading issue quick and dirty. That said, I won't fix it and focus on getting the new webinterface up and running.
